// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bill struct {
	BillID   int32
	UserID   pgtype.Int4
	TicketID []int32
}

type Cast struct {
	IDCast    int32
	Character pgtype.Text
	Name      pgtype.Text
	Gender    pgtype.Int4
}

type Cinema struct {
	CinemaID int32
	Name     pgtype.Text
}

type Coupon struct {
	ID                 int32
	Code               string
	Description        pgtype.Text
	DiscountPercentage pgtype.Int4
	ValidFrom          pgtype.Date
	ExpiresAt          pgtype.Date
}

type Crew struct {
	IDCrew int32
	Gender pgtype.Text
	Role   pgtype.Text
}

type Gerne struct {
	IDGerne int32
	Name    pgtype.Text
}

type Movie struct {
	MovieID          int32
	Title            pgtype.Text
	Overview         pgtype.Text
	OriginalLanguage pgtype.Text
	Ageres           pgtype.Int4
	ReleaseDate      pgtype.Date
	Status           pgtype.Text
	Tagline          pgtype.Text
	Length           pgtype.Int4
	Url              pgtype.Text
}

type MovieJoinCast struct {
	MovieID pgtype.Int4
	IDCast  pgtype.Int4
}

type MovieJoinCrew struct {
	MovieID pgtype.Int4
	IDCrew  pgtype.Int4
}

type MovieJoinGerne struct {
	MovieID pgtype.Int4
	IDGerne pgtype.Int4
}

type Price struct {
	PriceID int32
	Type    pgtype.Text
	Price   pgtype.Int4
}

type Room struct {
	RoomID   int32
	CinemaID pgtype.Int4
	Type     pgtype.Text
}

type Schedule struct {
	ScheduleID         int32
	ScheduleMovieDate  pgtype.Date
	ScheduleMovieStart pgtype.Time
	MovieID            pgtype.Int4
	RoomID             pgtype.Int4
	CinemaID           pgtype.Int4
}

type Seat struct {
	SeatID   int32
	RoomID   pgtype.Int4
	Rowss    pgtype.Text
	Columnss pgtype.Int4
}

type Ticket struct {
	ID         int32
	UserID     pgtype.Int4
	ScheduleID pgtype.Int4
	SeatID     pgtype.Int4
	Totalprice pgtype.Int4
	Coupon     pgtype.Int4
}

type User struct {
	UserID    int32
	Username  pgtype.Text
	Email     pgtype.Text
	BirthDate pgtype.Date
	Password  pgtype.Text
	Phone     pgtype.Text
}
