// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPassword = `-- name: GetUserPassword :one
SELECT password FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserPassword(ctx context.Context, email pgtype.Text) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserPassword, email)
	var password pgtype.Text
	err := row.Scan(&password)
	return password, err
}
